# Generated by Django 5.0.6 on 2024-07-08 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('volume_of_ingredients', models.FloatField()),
                ('description', models.TextField()),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.ingredients')),
                ('unit_of_ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.units')),
            ],
        ),
    ]
