# Generated by Django 4.2.16 on 2025-01-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipe_images/default.png', upload_to='recipe_images/'),
        ),
    ]
