# Generated by Django 5.0.7 on 2024-08-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='recipies',
            name='unit_of_ingredients',
        ),
        migrations.RemoveField(
            model_name='recipies',
            name='volume_of_ingredients',
        ),
        migrations.AddField(
            model_name='recipies',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
