# Generated by Django 5.0.7 on 2024-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_alter_recipies_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityOfIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipies',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=50)),
                ('quantity_of_ing', models.ManyToManyField(to='cookbook.quantityofingredient')),
                ('unit_of_ing', models.ManyToManyField(to='cookbook.unit')),
            ],
        ),
        migrations.AddField(
            model_name='recipies',
            name='ingredients',
            field=models.ManyToManyField(to='cookbook.ingredients'),
        ),
    ]
